channels:
  - conda-forge
dependencies:
  - fortran-compiler>=1.5.0
  - make>=4.3
  - bc>=1.07.1
  - bcrypt>=4.1.2
  - blas>=2.116
  - bash>=5.1.16
  - sudospawner>=0.5.2
  - pytest-shutil>=1.7.0
  - pytest-subprocess>=1.5.0
  - numpy>=1.26.4
  - scipy>=1.12.0
  - openblas>=0.3.26
  - libopenblas>=0.3.26
